spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=onetomany"
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 54320
